ListPosts = new Mongo.Collection("listposts")
Slides = new Mongo.Collection("slides")
Analytics = new Mongo.Collection("analytics")
GoogleKeys = new Mongo.Collection("googlekeys")
Leads = new Mongo.Collection("leads") 
